spring.application.name=monex

# SQLite
spring.datasource.url=jdbc:sqlite:${user.home}/.monex/monex.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# Liquibase owns the schema
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
